it would throw an exception and the program would fail.
